%% configs.m - CPCA Analysis Configuration File
% This file defines all parameters for the CPCA analysis

% Initialize empty config structure
config = struct();

% Base directory of fMRI-CPCA script
config.cpcaDIR = 'D:\fMRI-CPCA\fMRI-CPCA-cmd'; % Should be PATH/cpca_1.2.2.23

% Base directory containing your data
config.baseDIR = 'D:\fMRI-CPCA\Example_Data_2MergedTasks';

% Output directory (optional)
% If empty, output will be placed in baseDIR (legacy behaviour)
% If specified, all fMRI-CPCA output will be placed here instead
config.outputDIR = 'D:\fMRI-CPCA\mergedOutPut';  % e.g., 'D:\fMRI-CPCA\output'

% File wildcard for scan selection (e.g., 'swa*nii' or 'fsn*img')
config.filewildcard = '*nii';

% Mask parameters
config.maskName = 'mask.img';  % Name of the mask file
config.createMask = 1;  % 1 to create a new mask, 0 to use existing mask
config.maskMethod = 1;  % 1-Global mean threshold; 2-Harvard Oxford MNI coordinates

% Normalization parameters
config.linearRegress = 1;      % 1-On, 0-Off
config.quadraticRegress = 1;   % 1-On, 0-Off
config.movementRegress = 0;    % 1-On, 0-Off
config.userCovariants = '';    % Filename for user-defined covariants (leave empty if none)
config.meanCenter = 1;         % 1-On, 0-Off
config.standardize = 1;        % 1-On, 0-Off


% G matrix parameters
config.bins = 8;        % Number of time bins
config.TR = 3;          % Timing rate
config.inScans = 1;     % 1 for Scans timing, 0 for seconds
config.normalize_G = 1; % 1 to normalize G matrix, 0 to not normalize




% Component extraction parameters
config.solutions(1).num_components = 2;
config.solutions(1).rotation_method = 'varimax';
config.solutions(1).components_to_flip.unrotated = [1];      % flip component 1 in unrotated
config.solutions(1).components_to_flip.rotated   = [1 2];    % flip components 1 and 2 in varimax

% configs.m
config.solutions(1).num_components    = 2;
config.solutions(1).rotation_method   = 'hrfmax';
config.solutions(1).hrfmax_shapes_path = 'D:\fMRI-CPCA\Example_Data_2MergedTasks/shapes.mat';  % → hrf_file
config.solutions(1).hrfmax_shapes_var  = 'shapes';               % → hrf_mat (variable name inside the .mat)

%% ── Auto-generated by generate_config (do not edit manually) ──
config.num_subjects   = 7;
config.num_runs       = 9;
config.num_conditions = 10;
config.condition_names = { ...
    '4Letters_NoDelay', ...
    '4Letters_2Delay', ...
    '6Letters_NoDelay', ...
    '6Letters_2Delay', ...
    'pain_standard_high', ...
    'pain_standard_low', ...
    'pain_reg-up_high', ...
    'pain_reg-up_low', ...
    'pain_reg-down_high', ...
    'pain_reg-down_low'  ...
};
config.subject_conditions{1} = { [1  2  3  4] };  % PreSingle_VISION_V01: run-1
config.subject_conditions{2} = { [1  2  3  4] };  % PreSingle_VISION_V02: run-1
config.subject_conditions{3} = { [1  2  3  4] };  % PreSingle_VISION_V03: run-1
config.subject_conditions{4} = { [5  6], [5  6], [7  8], [5  6], [5  6], [5  6], [9  10], [5  6], [5  6] };  % sub-01: run-1, run-2, run-3, run-4, run-5, run-6, run-7, run-8, run-9
config.subject_conditions{5} = { [5  6], [5  6], [9  10], [5  6], [5  6], [5  6], [7  8], [5  6], [5  6] };  % sub-02: run-1, run-2, run-3, run-4, run-5, run-6, run-7, run-8, run-9
config.subject_conditions{6} = { [5  6], [5  6], [9  10], [5  6], [5  6], [5  6], [7  8], [5  6], [5  6] };  % sub-03: run-1, run-2, run-3, run-4, run-5, run-6, run-7, run-8, run-9
config.subject_conditions{7} = { [5  6], [5  6], [9  10], [5  6], [5  6], [5  6], [7  8], [5  6] };  % sub-04: run-1, run-2, run-3, run-4, run-5, run-6, run-7, run-8
%% ── End auto-generated ──
