%% configs.m - CPCA Analysis Configuration File
% This file defines all parameters for the CPCA analysis

% Initialize empty config structure
config = struct();

% Base directory of fMRI-CPCA script
config.cpcaDIR = 'D:\fMRI-CPCA\fMRI-CPCA-cmd'; % Should be PATH/cpca_1.2.2.23

% Base directory containing your data
config.baseDIR = 'D:\fMRI-CPCA\example_data_Multiple_Groups_Subjects_Runs';

% Output directory (optional)
% If empty, output will be placed in baseDIR (legacy behaviour)
% If specified, all fMRI-CPCA output will be placed here instead
config.outputDIR = 'D:\fMRI-CPCA\hrfMaxOutPut';  % e.g., 'D:\fMRI-CPCA\output'

% File wildcard for scan selection (e.g., 'swa*nii' or 'fsn*img')
config.filewildcard = 'fsn*img';

% Mask parameters
config.maskName = 'mask.img';  % Name of the mask file
config.createMask = 1;  % 1 to create a new mask, 0 to use existing mask
config.maskMethod = 2;  % 1-Global mean threshold; 2-Harvard Oxford MNI coordinates
config.removeVentricles = 0; % 1 to exclude ventricles, 0 to include ventricles

% Normalization parameters
config.linearRegress = 1;      % 1-On, 0-Off
config.quadraticRegress = 1;   % 1-On, 0-Off
config.movementRegress = 0;    % 1-On, 0-Off
config.userCovariants = '';    % Filename for user-defined covariants (leave empty if none)
config.meanCenter = 1;         % 1-On, 0-Off
config.standardize = 1;        % 1-On, 0-Off


% G matrix parameters
config.bins = 8;        % Number of time bins
config.TR = 3;          % Timing rate
config.inScans = 1;     % 1 for Scans timing, 0 for seconds
config.normalize_G = 1; % 1 to normalize G matrix, 0 to not normalize






% --- Solution 1: nd = 2 ---
config.solutions(1).num_components               = 2
config.solutions(1).components_to_flip.unrotated  = [1 2];
config.solutions(1).components_to_flip.rotated    = [1 2];




%% ── Auto-generated by generate_config (do not edit manually) ──
config.num_subjects   = 4;
config.num_runs       = 2;
config.num_conditions = 4;
config.condition_names = { ...
    '2_letters', ...
    '4_letters', ...
    '6_letters', ...
    '8_letters'  ...
};
config.subject_conditions{1} = { [1  2  3  4], [1  2  3  4] };  % s01: runa, runb
config.subject_conditions{2} = { [1  2  3  4], [1  2  3  4] };  % s03: wmla, wmlb
config.subject_conditions{3} = { [1  2  3  4], [1  2  3  4] };  % sz01: runa, runb
config.subject_conditions{4} = { [1  2  3  4], [1  2  3  4] };  % sz02: runa, runb
%% ── End auto-generated ──
