%% configs.m - CPCA Analysis Configuration File
% This file defines all parameters for the CPCA analysis

% Initialize empty config structure
config = struct();

% Base directory of fMRI-CPCA script
config.cpcaDIR = 'D:\fMRI-CPCA\fMRI-CPCA-cmd'; % Should be PATH/cpca_1.2.2.23

% Base directory containing your data
config.baseDIR = 'D:\fMRI-CPCA\example_data_Multiple_Groups_Subjects_Runs_new\example_data_Multiple_Groups_Subjects_Runs';

% Output directory (optional)
% If empty, output will be placed in baseDIR (legacy behaviour)
% If specified, all fMRI-CPCA output will be placed here instead
config.outputDIR = 'D:\fMRI-CPCA\hrfMaxOutPut';  % e.g., 'D:\fMRI-CPCA\output'

% File wildcard for scan selection (e.g., 'swa*nii' or 'fsn*img')
config.filewildcard = 'fsn*img';

% Mask parameters
config.maskName = 'mask.img';  % Name of the mask file
config.createMask = 1;  % 1 to create a new mask, 0 to use existing mask
config.maskMethod = 1;  % 1-Global mean threshold; 2-Harvard Oxford MNI coordinates

% Normalization parameters
config.linearRegress = 1;      % 1-On, 0-Off
config.quadraticRegress = 1;   % 1-On, 0-Off
config.movementRegress = 0;    % 1-On, 0-Off
config.userCovariants = '';    % Filename for user-defined covariants (leave empty if none)
config.meanCenter = 1;         % 1-On, 0-Off
config.standardize = 1;        % 1-On, 0-Off


% G matrix parameters
config.bins = 8;        % Number of time bins
config.TR = 3;          % Timing rate
config.inScans = 1;     % 1 for Scans timing, 0 for seconds
config.normalize_G = 1; % 1 to normalize G matrix, 0 to not normalize






config.solutions(1).num_components       = 2;
config.solutions(1).rotation_method      = 'hrfmax';
config.solutions(1).hrfmax_iterations    = 100000;        % optional, default 500000
config.solutions(1).hrfmax_events(1).onset       = 0;    % ms
config.solutions(1).hrfmax_events(1).duration    = 500;  % ms
config.solutions(1).hrfmax_events(1).description = 'visual onset';
config.solutions(1).hrfmax_events(2).onset       = 500;
config.solutions(1).hrfmax_events(2).duration    = 1000;
config.solutions(1).hrfmax_events(2).description = 'visual display';
config.solutions(1).hrfmax_events(3).onset       = 1500;
config.solutions(1).hrfmax_events(3).duration    = 1000;
config.solutions(1).hrfmax_events(3).description = 'response process';
% event 4 omitted — evaluation process excluded
config.solutions(1).components_to_flip.unrotated = [1 2];
config.solutions(1).components_to_flip.rotated   = [1 2];

% Component extraction parameters
config.solutions(2).num_components = 3;
config.solutions(2).rotation_method = 'varimax';
config.solutions(2).components_to_flip.unrotated = [1 3];      % flip component 1 in unrotated
config.solutions(2).components_to_flip.rotated   = [1 2];    % flip components 1 and 2 in varimax


%% ── Auto-generated by generate_config (do not edit manually) ──
config.num_subjects   = 4;
config.num_runs       = 2;
config.num_conditions = 4;
config.condition_names = { ...
    '2_letters', ...
    '4_letters', ...
    '6_letters', ...
    '8_letters'  ...
};
config.subject_conditions{1} = { [1  2  3  4], [1  2  3  4] };  % s01: runa, runb
config.subject_conditions{2} = { [1  2  3  4], [1  2  3  4] };  % s03: wmla, wmlb
config.subject_conditions{3} = { [1  2  3  4], [1  2  3  4] };  % sz01: runa, runb
config.subject_conditions{4} = { [1  2  3  4], [1  2  3  4] };  % sz02: runa, runb
%% ── End auto-generated ──
