function Good_T = hrfmax_hillclimb( P, U, shapes, load_state, pop )
% -----------------------------------------------------------------------
% hrfmax_hillclimb
%
% Experimental replacement for hrfmax.m's search strategy.
%
% Instead of drawing a fresh random T every iteration and keeping only
% the single best-ever result (pure random search), this version uses
% random-restart hill climbing:
%
%   - each restart begins from a fresh, independent random T (rand_T)
%   - within a restart ("climb"), candidates are generated by nudging
%     the climb-local current T and re-running the same valid-T
%     construction recipe that rand_T uses (build_T_from_seed)
%   - the step size used to nudge shrinks/reset on a cosine
%     warm-restart schedule within each climb
%   - a climb stops when its step size collapses or it stalls for too
%     long without a locally-improving step
%   - restarts stop once several in a row fail to beat the all-time
%     best score (adaptive patience), or a safety cap (8*nd) is hit
%
% NOTE: the "iterations" parameter from hrfmax.m is intentionally not
% part of this function's interface -- it has no meaning here, since
% this algorithm self-terminates rather than running a fixed count.
%
% State is persisted separately from hrfmax.m's own state/T files, so
% the two versions can be run side-by-side without collision:
%   hrfmax_hillclimb_state.mat   (pause/resume, restart-granularity only)
%   hrfmax_hillclimb_T.mat       (best T found so far)
% -----------------------------------------------------------------------

  Good_T = [];

  if ( nargin < 3 )
    error( 'hrfmax_hillclimb: need at least 3 parameters.' );
  end;

  if ( nargin < 4 )
    load_state = 0;
  end;

  if ( nargin < 5 )
    pop = 0;
  end;
  if ~strcmp( class(pop), 'cpca_progress' )
    pop = [];
  end

  if ~isempty(pop)
    pop.setForHRFMAX();
    pop.activateSaveState();
    pop.setComment( 'Calculating T Matrix (hill climbing)' );
  end;


  if load_state

    load hrfmax_hillclimb_state

  else

    state = struct( ...
      'Good_T', [], ...
      'totcorr', 0, ...
      'info', [0;0;0], ...
      'U', U, ...
      'P', P, ...
      'num_shapes', 0, ...
      'num_bins', 0, ...
      'num_components', 0, ...
      'num_all_conditions', 0, ...
      'all_shapes', 0, ...
      'all_component_max_correlations', [], ...
      'restart_count', 0, ...
      'no_improve_count', 0, ...
      'patience', 3, ...
      'max_stall', 15, ...
      'max_step', 0.3, ...
      'min_step', 1e-4, ...
      'cycle_length', 50, ...
      'improve_tol', 1e-6 ...
    );

    [state.num_shapes state.num_bins] = size(shapes);
    state.num_components = size(P,2);
    state.num_all_conditions = floor( size(state.P,1)/state.num_bins );		% number of conditions * (subjects * runs)

    if ( state.num_all_conditions * state.num_bins  ~= size(P,1) )
      error( 'P_unrotated and shapes do not correspond to each other' );
    end;

    state.all_shapes = zeros( size(shapes,1), size(shapes, 2) * state.num_all_conditions );
    ec = 0;
    for ii = 1:state.num_all_conditions
      sc = ec + 1;
      ec = sc + size(shapes,2) - 1;
      state.all_shapes(:, sc:ec) = shapes;
    end;

    state.all_component_max_correlations = zeros(1, state.num_components );

  end;

  if ~isempty(pop)
    pop.setComment( 'Calculating T Matrix (hill climbing)' );
    pop.setStateInfo( state.info(1), state.info(2), state.info(3) );
  end;

  Good_T = calc_href_T_matrix_hillclimb( state, pop );

  if ~isempty(pop)
    pop.deactivateSaveState();
    pop.unsetHRFMAX();
  end;



% -----------------------------------------------------------------------
% main calculation process - random-restart hill climbing
% -----------------------------------------------------------------------
function Good_T = calc_href_T_matrix_hillclimb( state, pop )

  nd = state.num_components;
  max_restarts_cap = 8 * nd;   % safety ceiling only, scales with problem size

  while state.no_improve_count < state.patience && state.restart_count < max_restarts_cap

    % --- pause check: once per restart, not per inner climb-step ---
    if ~isempty(pop)
      x = pop.getSaveState();
      if x
        state.info = pop.getStateInfo();
        save hrfmax_hillclimb_state state
        Good_T = [];
        pop.unsetHRFMAX();
        return;
      end;
      pop.incrementHrfmax();
    end;

    state.restart_count = state.restart_count + 1;
    fprintf( ' - hrfmax_hillclimb: restart %3d (best so far: %.6f)\n', state.restart_count, state.totcorr );

    % -----------------------------------------------------
    % start this climb from a fresh, independent random T
    % -----------------------------------------------------
    T = rand_T( state.U );
    climb_score = -Inf;
    stall_count = 0;
    t = 0;

    while stall_count < state.max_stall

      t = t + 1;

      % --- cosine warm-restart step size, within this climb ---
      cycle_t = mod(t, state.cycle_length);
      step_size = state.min_step + 0.5*(state.max_step - state.min_step) * ...
                  (1 + cos(pi * cycle_t / state.cycle_length));

      if step_size <= state.min_step
        break;    % step has collapsed -- this climb is done
      end;

      % --- nudge the climb-local current T and rebuild validly ---
      T_candidate = perturb_T( T, state.U, step_size );

      % -----------------------------------------------------
      % evaluate this candidate (unchanged objective from hrfmax.m)
      % -----------------------------------------------------
      RotatedP = state.P * inv(T_candidate');

      state.all_component_max_correlations = state.all_component_max_correlations .* 0;
      for this_component = 1:state.num_components
        x = abs(corrcoef([RotatedP(:,this_component) state.all_shapes' ]));
        state.all_component_max_correlations( this_component ) = max( x(2:end, 1 ) );
      end;

      score = prod(state.all_component_max_correlations );

      % --- local comparison: is this climb still making progress? ---
      if score > climb_score
        T = T_candidate;
        climb_score = score;
        stall_count = 0;
      else
        stall_count = stall_count + 1;
      end;

      % --- global comparison: new all-time best? save immediately ---
      if score > state.totcorr
        state.totcorr = score;
        state.Good_T  = T_candidate;

        if ~isempty(pop)
          pop.flagTChange( pop.SECONDARY );
        end;
        save hrfmax_hillclimb_T T_candidate
      end;

    end;
    % --- end of one climb ---

    if climb_score >= state.totcorr - state.improve_tol
      state.no_improve_count = 0;
    else
      state.no_improve_count = state.no_improve_count + 1;
    end;

  end;

  Good_T = state.Good_T;

  if exist( 'hrfmax_hillclimb_state.mat', 'file' )
    delete hrfmax_hillclimb_state.mat
  end;



% -----------------------------------------------------------------------
% same valid-T construction rand_T uses, factored out so a nudged seed
% (instead of pure random noise) can be run through it too
% -----------------------------------------------------------------------
function T = build_T_from_seed( seed, U )

  T = seed;
  UR = U*T(:,1);
  for i = 2:size(U,2)
    D = U*T(:,i);
    D = D - UR*(inv(UR'*UR)*UR'*D);
    T(:,i) = inv(U'*U)*U'*D;
    if norm(D,1) > exp(-32)
      UR = [UR D];
    end;
  end;
  T = T./(ones(size(T,1),1)*sqrt(sum(T.^2)));



% -----------------------------------------------------------------------
% nudge the climb-local current T by adding noise to a seed derived
% from it, then rebuilding validly via the same recipe rand_T uses.
% T itself is never perturbed directly, since doing so would break its
% orthogonality/normalization structure relative to U.
% -----------------------------------------------------------------------
function T = perturb_T( T_prev, U, step_size )
  seed = T_prev + step_size * randn(size(T_prev));
  T = build_T_from_seed( seed, U );

